name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change to 'master' if that's your default branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site from DEMO/ folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: DEMO  # this must match the folder that contains index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
