name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your repo's default branch if needed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  # ✅ Updated to latest

      - name: Upload site from DEMO folder
        uses: actions/upload-pages-artifact@v3  # ✅ Use latest version
        with:
          path: demo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # ✅ Updated version
