name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

permissions:
  contents: write  # needed to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: DEMO  # this is where your index.html is located

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
